#!/bin/sh

# Firefox
flatpak install flathub org.mozilla.firefox -y

# Spotify 
flatpak install flathub com.spotify.Client -y

# IntelliJ-Community
flatpak install flathub com.jetbrains.IntelliJ-IDEA-Community -y

# Pycharm-Community
flatpak install flathub com.jetbrains.PyCharm-Community -y

# Visual Studio Code
flatpak install flathub com.visualstudio.code -y

# Figma
flatpak install flathub io.github.Figma_Linux.figma_linux -y

# Dbeaver
flatpak install flathub io.dbeaver.DBeaverCommunity -y

# Postman
flatpak install flathub com.getpostman.Postman -y
